version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/webapp" 
    schedule:
      interval: "daily" 
  - package-ecosystem: "npm"  
    directory: "/webapp"          
    schedule:
      interval: "daily"
